### PR TITLE
Support xAuth

### PR DESCRIPTION
**Pull request by pihao**

### CODE REVIEW

**Comment by garyburd** [comment]
What problem does this fix?

**Comment by pihao** [comment]
@garyburd I use it for 500px API, and not need the verify code from redirect URL. Get access token by username and password directly. So need this parameter.

**Comment by garyburd** [comment]
Please provide a link to the doc for API you are working with.

**Comment by pihao** [comment]
In fact, this pull request is xAuth support.
[Twitter xAuth API documents](https://dev.twitter.com/oauth/xauth)
[500px xAuth example (ruby)](https://github.com/500px/api-documentation/blob/master/examples/Ruby/xauth.rb)

**Comment by garyburd** [comment]
Add this method:

    // RequestTokenXAuth requests token credentials from the server using the xAuth protocol.
    // See https://dev.twitter.com/oauth/xauth for information on xAuth.
    func (c *Client) RequestTokenXAuth(client *http.Client, temporaryCredentials *Credentials, user, password string) (*Credentials, url.Values, error) {
    }

Add an example for 500px [here](https://github.com/garyburd/go-oauth/tree/master/examples).

**Comment by garyburd** [comment]
The latest PR does not compile. Please compile and test the code before pushing new changes to review.

**Comment by pihao** [comment]
Sorry! It's an accident! I am working with it.

**Comment by pihao** [comment]
I cleanup my old commit. Now test passed.

**Comment by garyburd** [comment]
Always set the parameters to handle case where service allows blank username or password.

**Comment by pihao** [comment]
@garyburd 👏 👏 👏

**Pull request merged**
