### PR TITLE
Adds oauth_verifier param to request header

### PR DESCRIPTION
**Pull request by justinhillsjohnson**
Fixes an authorization issue with Garmin's Wellness API.

@garyburd Let me know if you have any questions or would like changes made.

### CODE REVIEW

**Comment by garyburd** [comment]
Please provide more detail about why this change is needed.

**Comment by justinhillsjohnson** [comment]
Garmin has a private API that exposes wearable device data. While the specifics of the API are confidential, I can say that they have an `access_token` endpoint, which is stated to meet specs from http://oauth.net/core/1.0a/#auth_step3. Their endpoint requires the `oauth_verifier` param in the Authorization header, so our proposed fix in this PR simply sets the value and adds to `oauthKeys`, which is already iterated over in `authorizationHeader()`

**Comment by garyburd** [comment]
The [method for requesting token credentials](https://godoc.org/github.com/garyburd/go-oauth/oauth#Client.RequestToken) has a verifier parameter. Is there a reason why you cannot use this method?

**Comment by garyburd** [comment]
Can you use the [RequestToken](https://godoc.org/github.com/garyburd/go-oauth/oauth#Client.RequestToken) method for step 3? If not, can you explain why it does not work?

**Comment by justinhillsjohnson** [comment]
Thanks for your quick responses, Gary. We're already using `RequestToken()`. The problem is that the `oauth_verifier` param only gets sent in the signature and not in the Authorization headers. Without the patch in this PR, we get this response from Garmin's API:

``` SetAuthorizationHeader OAuth oauth_consumer_key="56af17e5-bea5-4433-b668-fbcd159c9a40", oauth_nonce="b3deadda4910b41", oauth_signature="896pGSZozcQVJeaPmSOPAHxojMs%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1496260801", oauth_token="49cadb2a-68ac-4986-9042-c6c053e80b8c", oauth_version="1.0"
{"time":"2017-05-22T16:11:26.921279352-06:00","level":"INFO","prefix":"-","file":"access_token.go","line":"25","message":"Garmin callback access token params: map[]"}
ERRO[1081] accessErr: OAuth server status 400, <html><head><title></title></head><body><h1>HTTP Status 400 - Missing verifier.</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Missing verifier.</u></p><p><b>description</b> <u>The request sent by the client was syntactically incorrect (Missing verifier.).</u></p></body></html> ```

**Comment by garyburd** [comment]
OK, I see now. 

With this PR, the verifier is included in the header and the form.  If I understand the specs correctly, the verifier should only be included in the header. 

My preferred fix is to add `oauthParms  url.Values` argument to `requestCredentials`, `do`, `authorizationHeader` and `oauthParams`.  The RequestToken method creates `oauthParams` with the verifier.  The `oauthParms` function uses the supplied params if not nil.

My preferred fix and the change in this PR both require careful testing.

I'll go ahead and make the change.

**Comment by garyburd** [comment]
Please try #28.

**Comment by moderation** [comment]
As someone who uses your code in my homemade Twitter client I'd just like to say thanks for being cautious with your code and open to fixes and upgrades where they make sense. This is a good example. Thanks for laying out your concerns.

**Comment by justinhillsjohnson** [comment]
Confirmed working. Closing this PR.

**Comment by garyburd** [comment]
@justinhillsjohnson Thank you for the help in identifying the issue. I'll merge the PR after more testing this afternoon.

**Comment by justinhillsjohnson** [comment]
Thanks, Gary. Much appreciated for all your hard work.

**Pull request closed without merging**
